// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: userauthn/userauthnpb/userauthnservice.proto

package userauthnpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VerifyUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *VerifyUser) Reset() {
	*x = VerifyUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUser) ProtoMessage() {}

func (x *VerifyUser) ProtoReflect() protoreflect.Message {
	mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUser.ProtoReflect.Descriptor instead.
func (*VerifyUser) Descriptor() ([]byte, []int) {
	return file_userauthn_userauthnpb_userauthnservice_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifiedUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *VerifiedUser) Reset() {
	*x = VerifiedUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifiedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedUser) ProtoMessage() {}

func (x *VerifiedUser) ProtoReflect() protoreflect.Message {
	mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedUser.ProtoReflect.Descriptor instead.
func (*VerifiedUser) Descriptor() ([]byte, []int) {
	return file_userauthn_userauthnpb_userauthnservice_proto_rawDescGZIP(), []int{1}
}

func (x *VerifiedUser) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type CreateTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyUser *VerifyUser `protobuf:"bytes,1,opt,name=verifyUser,proto3" json:"verifyUser,omitempty"`
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_userauthn_userauthnpb_userauthnservice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenRequest) GetVerifyUser() *VerifyUser {
	if x != nil {
		return x.VerifyUser
	}
	return nil
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verifieduser *VerifiedUser `protobuf:"bytes,1,opt,name=verifieduser,proto3" json:"verifieduser,omitempty"`
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_userauthn_userauthnpb_userauthnservice_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTokenResponse) GetVerifieduser() *VerifiedUser {
	if x != nil {
		return x.Verifieduser
	}
	return nil
}

var File_userauthn_userauthnpb_userauthnservice_proto protoreflect.FileDescriptor

var file_userauthn_userauthnpb_userauthnservice_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x75, 0x73, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x75, 0x74, 0x68, 0x6e, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x70, 0x62, 0x22, 0x3e, 0x0a, 0x0a, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x31, 0x0a, 0x0c, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4d,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61,
	0x75, 0x74, 0x68, 0x6e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x22, 0x54, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x75,
	0x73, 0x65, 0x72, 0x32, 0x64, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x75, 0x74,
	0x68, 0x6e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x75,
	0x74, 0x68, 0x6e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x75,
	0x73, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_userauthn_userauthnpb_userauthnservice_proto_rawDescOnce sync.Once
	file_userauthn_userauthnpb_userauthnservice_proto_rawDescData = file_userauthn_userauthnpb_userauthnservice_proto_rawDesc
)

func file_userauthn_userauthnpb_userauthnservice_proto_rawDescGZIP() []byte {
	file_userauthn_userauthnpb_userauthnservice_proto_rawDescOnce.Do(func() {
		file_userauthn_userauthnpb_userauthnservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_userauthn_userauthnpb_userauthnservice_proto_rawDescData)
	})
	return file_userauthn_userauthnpb_userauthnservice_proto_rawDescData
}

var file_userauthn_userauthnpb_userauthnservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userauthn_userauthnpb_userauthnservice_proto_goTypes = []interface{}{
	(*VerifyUser)(nil),          // 0: userauthnpb.VerifyUser
	(*VerifiedUser)(nil),        // 1: userauthnpb.VerifiedUser
	(*CreateTokenRequest)(nil),  // 2: userauthnpb.CreateTokenRequest
	(*CreateTokenResponse)(nil), // 3: userauthnpb.CreateTokenResponse
}
var file_userauthn_userauthnpb_userauthnservice_proto_depIdxs = []int32{
	0, // 0: userauthnpb.CreateTokenRequest.verifyUser:type_name -> userauthnpb.VerifyUser
	1, // 1: userauthnpb.CreateTokenResponse.verifieduser:type_name -> userauthnpb.VerifiedUser
	2, // 2: userauthnpb.UserAuthnService.CreateToken:input_type -> userauthnpb.CreateTokenRequest
	3, // 3: userauthnpb.UserAuthnService.CreateToken:output_type -> userauthnpb.CreateTokenResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_userauthn_userauthnpb_userauthnservice_proto_init() }
func file_userauthn_userauthnpb_userauthnservice_proto_init() {
	if File_userauthn_userauthnpb_userauthnservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifiedUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userauthn_userauthnpb_userauthnservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userauthn_userauthnpb_userauthnservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userauthn_userauthnpb_userauthnservice_proto_goTypes,
		DependencyIndexes: file_userauthn_userauthnpb_userauthnservice_proto_depIdxs,
		MessageInfos:      file_userauthn_userauthnpb_userauthnservice_proto_msgTypes,
	}.Build()
	File_userauthn_userauthnpb_userauthnservice_proto = out.File
	file_userauthn_userauthnpb_userauthnservice_proto_rawDesc = nil
	file_userauthn_userauthnpb_userauthnservice_proto_goTypes = nil
	file_userauthn_userauthnpb_userauthnservice_proto_depIdxs = nil
}
