// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mongodbhealthpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MongoDbHealthServiceClient is the client API for MongoDbHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MongoDbHealthServiceClient interface {
	// https://developers.google.com/protocol-buffers/docs/proto3#any
	// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty
	GetMongoDBHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMongoDBHealthResponse, error)
}

type mongoDbHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMongoDbHealthServiceClient(cc grpc.ClientConnInterface) MongoDbHealthServiceClient {
	return &mongoDbHealthServiceClient{cc}
}

func (c *mongoDbHealthServiceClient) GetMongoDBHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMongoDBHealthResponse, error) {
	out := new(GetMongoDBHealthResponse)
	err := c.cc.Invoke(ctx, "/mongodbhealthpb.MongoDbHealthService/GetMongoDBHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoDbHealthServiceServer is the server API for MongoDbHealthService service.
// All implementations must embed UnimplementedMongoDbHealthServiceServer
// for forward compatibility
type MongoDbHealthServiceServer interface {
	// https://developers.google.com/protocol-buffers/docs/proto3#any
	// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty
	GetMongoDBHealth(context.Context, *emptypb.Empty) (*GetMongoDBHealthResponse, error)
	mustEmbedUnimplementedMongoDbHealthServiceServer()
}

// UnimplementedMongoDbHealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMongoDbHealthServiceServer struct {
}

func (UnimplementedMongoDbHealthServiceServer) GetMongoDBHealth(context.Context, *emptypb.Empty) (*GetMongoDBHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMongoDBHealth not implemented")
}
func (UnimplementedMongoDbHealthServiceServer) mustEmbedUnimplementedMongoDbHealthServiceServer() {}

// UnsafeMongoDbHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MongoDbHealthServiceServer will
// result in compilation errors.
type UnsafeMongoDbHealthServiceServer interface {
	mustEmbedUnimplementedMongoDbHealthServiceServer()
}

func RegisterMongoDbHealthServiceServer(s grpc.ServiceRegistrar, srv MongoDbHealthServiceServer) {
	s.RegisterService(&_MongoDbHealthService_serviceDesc, srv)
}

func _MongoDbHealthService_GetMongoDBHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDbHealthServiceServer).GetMongoDBHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodbhealthpb.MongoDbHealthService/GetMongoDBHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDbHealthServiceServer).GetMongoDBHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MongoDbHealthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mongodbhealthpb.MongoDbHealthService",
	HandlerType: (*MongoDbHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMongoDBHealth",
			Handler:    _MongoDbHealthService_GetMongoDBHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mongodbhealth/mongodbhealthpb/mongodbhealthservice.proto",
}
