# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  deposits_shared_grpc_network:
    driver: bridge

services:

  # This starts a local Mongodb
  depositsmongodb:
    container_name: deposits_mongodb
    networks:
      - deposits_shared_grpc_network
    image: mongo:4.4.2-bionic
    ports:
      - 27017:27017
    volumes:
      - ./mongo-compose-volume:/data/db

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - deposits_shared_grpc_network
    image: openzipkin/zipkin:2.23
    ports:
      - 9411:9411
