// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: api/interestcalpb/intrestcalservice.proto

package interestcalpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account     string  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AccountType string  `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Apy         float64 `protobuf:"fixed64,3,opt,name=apy,proto3" json:"apy,omitempty"`
	Years       float64 `protobuf:"fixed64,4,opt,name=years,proto3" json:"years,omitempty"`
	Amount      float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *NewDeposit) Reset() {
	*x = NewDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDeposit) ProtoMessage() {}

func (x *NewDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDeposit.ProtoReflect.Descriptor instead.
func (*NewDeposit) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{0}
}

func (x *NewDeposit) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *NewDeposit) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *NewDeposit) GetApy() float64 {
	if x != nil {
		return x.Apy
	}
	return 0
}

func (x *NewDeposit) GetYears() float64 {
	if x != nil {
		return x.Years
	}
	return 0
}

func (x *NewDeposit) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Deposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account     string  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AccountType string  `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Apy         float64 `protobuf:"fixed64,3,opt,name=apy,proto3" json:"apy,omitempty"`
	Years       float64 `protobuf:"fixed64,4,opt,name=years,proto3" json:"years,omitempty"`
	Amount      float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Delta       float64 `protobuf:"fixed64,6,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{1}
}

func (x *Deposit) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Deposit) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Deposit) GetApy() float64 {
	if x != nil {
		return x.Apy
	}
	return 0
}

func (x *Deposit) GetYears() float64 {
	if x != nil {
		return x.Years
	}
	return 0
}

func (x *Deposit) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Deposit) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type NewBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewDeposits []*NewDeposit `protobuf:"bytes,2,rep,name=new_deposits,json=newDeposits,proto3" json:"new_deposits,omitempty"`
}

func (x *NewBank) Reset() {
	*x = NewBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBank) ProtoMessage() {}

func (x *NewBank) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBank.ProtoReflect.Descriptor instead.
func (*NewBank) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{2}
}

func (x *NewBank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewBank) GetNewDeposits() []*NewDeposit {
	if x != nil {
		return x.NewDeposits
	}
	return nil
}

type Bank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Deposits []*Deposit `protobuf:"bytes,2,rep,name=deposits,proto3" json:"deposits,omitempty"`
	Delta    float64    `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *Bank) Reset() {
	*x = Bank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{3}
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *Bank) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type CreateInterestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewBanks []*NewBank `protobuf:"bytes,1,rep,name=new_banks,json=newBanks,proto3" json:"new_banks,omitempty"`
}

func (x *CreateInterestRequest) Reset() {
	*x = CreateInterestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInterestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterestRequest) ProtoMessage() {}

func (x *CreateInterestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterestRequest.ProtoReflect.Descriptor instead.
func (*CreateInterestRequest) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInterestRequest) GetNewBanks() []*NewBank {
	if x != nil {
		return x.NewBanks
	}
	return nil
}

type CreateInterestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banks []*Bank `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	Delta float64 `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *CreateInterestResponse) Reset() {
	*x = CreateInterestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInterestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterestResponse) ProtoMessage() {}

func (x *CreateInterestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_interestcalpb_intrestcalservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterestResponse.ProtoReflect.Descriptor instead.
func (*CreateInterestResponse) Descriptor() ([]byte, []int) {
	return file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInterestResponse) GetBanks() []*Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

func (x *CreateInterestResponse) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_api_interestcalpb_intrestcalservice_proto protoreflect.FileDescriptor

var file_api_interestcalpb_intrestcalservice_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61,
	0x6c, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x22, 0x89, 0x01, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x61, 0x70, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x70, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x70, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x79, 0x65, 0x61, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x22, 0x62,
	0x0a, 0x04, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x52, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65, 0x6c,
	0x74, 0x61, 0x22, 0x4a, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x6e,
	0x65, 0x77, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x77,
	0x42, 0x61, 0x6e, 0x6b, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x42, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x57,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x61, 0x6e, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65,
	0x73, 0x74, 0x63, 0x61, 0x6c, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x05, 0x62, 0x61, 0x6e, 0x6b,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x32, 0x6f, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61,
	0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x63, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_interestcalpb_intrestcalservice_proto_rawDescOnce sync.Once
	file_api_interestcalpb_intrestcalservice_proto_rawDescData = file_api_interestcalpb_intrestcalservice_proto_rawDesc
)

func file_api_interestcalpb_intrestcalservice_proto_rawDescGZIP() []byte {
	file_api_interestcalpb_intrestcalservice_proto_rawDescOnce.Do(func() {
		file_api_interestcalpb_intrestcalservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_interestcalpb_intrestcalservice_proto_rawDescData)
	})
	return file_api_interestcalpb_intrestcalservice_proto_rawDescData
}

var file_api_interestcalpb_intrestcalservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_interestcalpb_intrestcalservice_proto_goTypes = []interface{}{
	(*NewDeposit)(nil),             // 0: interestcal.NewDeposit
	(*Deposit)(nil),                // 1: interestcal.Deposit
	(*NewBank)(nil),                // 2: interestcal.NewBank
	(*Bank)(nil),                   // 3: interestcal.Bank
	(*CreateInterestRequest)(nil),  // 4: interestcal.CreateInterestRequest
	(*CreateInterestResponse)(nil), // 5: interestcal.CreateInterestResponse
}
var file_api_interestcalpb_intrestcalservice_proto_depIdxs = []int32{
	0, // 0: interestcal.NewBank.new_deposits:type_name -> interestcal.NewDeposit
	1, // 1: interestcal.Bank.deposits:type_name -> interestcal.Deposit
	2, // 2: interestcal.CreateInterestRequest.new_banks:type_name -> interestcal.NewBank
	3, // 3: interestcal.CreateInterestResponse.banks:type_name -> interestcal.Bank
	4, // 4: interestcal.InterestCalService.CreateInterest:input_type -> interestcal.CreateInterestRequest
	5, // 5: interestcal.InterestCalService.CreateInterest:output_type -> interestcal.CreateInterestResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_interestcalpb_intrestcalservice_proto_init() }
func file_api_interestcalpb_intrestcalservice_proto_init() {
	if File_api_interestcalpb_intrestcalservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInterestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interestcalpb_intrestcalservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInterestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_interestcalpb_intrestcalservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_interestcalpb_intrestcalservice_proto_goTypes,
		DependencyIndexes: file_api_interestcalpb_intrestcalservice_proto_depIdxs,
		MessageInfos:      file_api_interestcalpb_intrestcalservice_proto_msgTypes,
	}.Build()
	File_api_interestcalpb_intrestcalservice_proto = out.File
	file_api_interestcalpb_intrestcalservice_proto_rawDesc = nil
	file_api_interestcalpb_intrestcalservice_proto_goTypes = nil
	file_api_interestcalpb_intrestcalservice_proto_depIdxs = nil
}
