// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package usermgmtpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// UserMgmtServiceClient is the client API for UserMgmtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMgmtServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type userMgmtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMgmtServiceClient(cc grpc.ClientConnInterface) UserMgmtServiceClient {
	return &userMgmtServiceClient{cc}
}

func (c *userMgmtServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/usermgmtpb.UserMgmtService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMgmtServiceServer is the server API for UserMgmtService service.
// All implementations must embed UnimplementedUserMgmtServiceServer
// for forward compatibility
type UserMgmtServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedUserMgmtServiceServer()
}

// UnimplementedUserMgmtServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserMgmtServiceServer struct {
}

func (UnimplementedUserMgmtServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserMgmtServiceServer) mustEmbedUnimplementedUserMgmtServiceServer() {}

// UnsafeUserMgmtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMgmtServiceServer will
// result in compilation errors.
type UnsafeUserMgmtServiceServer interface {
	mustEmbedUnimplementedUserMgmtServiceServer()
}

func RegisterUserMgmtServiceServer(s grpc.ServiceRegistrar, srv UserMgmtServiceServer) {
	s.RegisterService(&_UserMgmtService_serviceDesc, srv)
}

func _UserMgmtService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgmtServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgmtpb.UserMgmtService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgmtServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMgmtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usermgmtpb.UserMgmtService",
	HandlerType: (*UserMgmtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserMgmtService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/usermgmtpb/usermgmtservice.proto",
}
